
# Legendary Tooltips Configuration Instructions
#
# *** READ THIS FIRST ***
#
# By default, this mod does not apply special borders to most items.  It was designed to work well with mod packs where
# the available selection of items can vary widely, so it is up to the user or mod pack designer to customize as needed.
# There are many options available for setting up which custom borders (also called frames) apply to which items.  Follow these steps:
#   1. Decide which items you want to have custom borders, and which borders.  Note that each custom border has a number associated with it (starting at 0).
#   2. For each custom border you want to use, fill out the associated list in the "definitions" section.  This will be filled out with a list of "selectors",
#      each of which tell the mod what items have that border.  Please read the information above the definitions section for specifics.
#   3. Selectors for borders are checked in the order provided in the "priorities" section.  Once a match is found, that border is displayed.
#      For example, if border 0 had the selector "%Diamond" and border 1 had the selector "diamond_sword", they would both match for diamond swords.
#      In this case, whichever border number came first in the priority list would be the border that would get drawn in-game.
#   4. Optionally, border colors associated with custom borders can be set in the "colors" section.  The start color is the color at the top of the tooltip,
#      and the end color is the bottom, with a smooth transition between.  Please read the information above the color section for specifics.
[client]

	[client.visual_options]
		# Whether item names in tooltips should have a line under them separating them from the rest of the tooltip.
		name_separator = true
		# If enabled, tooltip border colors will match item rarity colors (except for custom borders).
		borders_match_rarity = true
		# If enabled, tooltips will display a drop shadow.
		tooltip_shadow = true
		# If enabled, items showing a custom border will have a special shine effect when hovered over.
		shine_effect = true
		# If enabled, tooltip titles will be drawn centered.
		centered_title = true
		# If enabled, tooltips with custom borders will always be at least wide enough to display all border decorations.
		enforce_minimum_width = false

	# Entry types:
	#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: "minecraft:stick", "iron_ore"
	#    Tag - $ followed by tag name.  Examples: "$forge:stone", "$planks"
	#    Mod name - @ followed by mod identifier.  Examples: "@spoiledeggs"
	#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: "!uncommon", "!rare", "!epic"
	#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: "#23F632"
	#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: "%Netherite", "%[Uncommon]"
	#    Tooltip text - Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: "^Legendary"
	#    NBT tag - & followed by tag name and optional comparator (=, >, <, or !=) and value, in the format <tag><comparator><value> or just <tag>.  Examples: "&Damage=0", "&Tier>1", "&map!=128", "&Enchantments"
	[client.definitions]
		level0_entries = ["netherite_sword", "netherite_shovel", "netherite_pickaxe", "netherite_axe", "netherite_hoe", "netherite_helmet", "netherite_chestplate",
							"netherite_leggings", "netherite_boots", "!epic"]
		level1_entries = ["diamond_sword", "diamond_shovel", "diamond_pickaxe", "diamond_axe", "diamond_hoe", "diamond_helmet", "diamond_chestplate", "diamond_leggings",
							"diamond_boots", "enchanted_book", "turtle_helmet", "tipped_arrow", "spectral_arrow", "!rare"]
		level2_entries = ["iron_sword", "iron_shovel", "iron_pickaxe", "iron_axe", "iron_hoe", "iron_helmet", "iron_chestplate", "iron_leggings", "iron_boots",
							"golden_sword", "golden_shovel", "golden_pickaxe", "golden_axe", "golden_hoe", "golden_helmet", "golden_chestplate", "golden_leggings",
							"golden_boots", "%Chainmail", "compass", "clock", "spyglass", "shears", "%Bucket", "lead", "name_tag", "flint_and_steel", "bow", "crossbow",
							"trident", "shield"]
		level3_entries = ["%Nether B", "%Nether Q", "%Nether G", "netherrack", "%Nylium", "crimson_fungus", "warped_fungus", "campfire", "fire_charge", "%Firework", "%Lava",
							"crimson_roots", "crimson_roots", "weeping_vines", "twisting_vines", "%Blast Furnace", "brewing_stand", "nether_wart",
							"telepastries:nether_cake", ""]
		level4_entries = ["sea_lantern", "heart_of_the_sea", "%Prismarine", "conduit", "nautilus_shell", "kelp", "seagrass", "sea_pickle", "%Coral"]
		level5_entries = ["$minecraft:small_flowers", "$minecraft:flowers", "$minecraft:leaves", "$minecraft:saplings", "$minecraft:tall_flowers", "%Azalea", "%Dripleaf",
							"%Vines", "bamboo", "%Root", "%Moss", "%Farmland", "%Blossom", "sugar_cane", "%Mushroom", "%Fern", "%Grass", "%Lily",
							"telepastries:overworld_cake", "telepastries:twilight_cake", "%Bush"]
		level6_entries = ["%Skull", "wither_rose", "%Obsidian", "respawn_anchor", "%Soul"]
		level7_entries = ["iron_door", "iron_trapdoor", "iron_block", "%Anvil", "%Minecart", "%Rail", "hopper", "observer", "dispenser", "dropper", "%Piston", "%Factory",
							"%Chain"]
		level8_entries = ["%End", "%Purpur", "%Chorus", "%Shulker"]
		level9_entries = ["elytra", "%Glow", "totem_of_undying", "experience_bottle", "golden_carrot", "golden_apple", "enchanted_golden_apple"]
		level10_entries = []
		level11_entries = []
		level12_entries = []
		level13_entries = []
		level14_entries = []
		level15_entries = []
		# Enter blacklist selectors here using the same format as above. Any items that match these selectors will NOT show a border.
		blacklist = []

	# Set border priorities here.  This should be a list of numbers that correspond to border levels, with numbers coming first being higher priority.
	# Optionally, -1 can be inserted to indicate relative priority of data and api-defined borders.  If you don't know what that means, you don't need to worry about it.
	[client.priorities]
		priorities = [3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 10, 11, 12, 13, 14, 15]

	# The colors used for each tooltip, in this order: top border color, bottom border color, top background color, bottom background color.
	# None of these colors are required, though any colors not specified will be replaced with the default tooltip colors.
	#
	# VALID COLOR FORMATS
	#   Hex color code - A hex color code is preceded by # or 0x and must be quoted.  Supports 3, 4, 6, or 8 digit codes in the formats RGB, ARGB, RRGGBB, AARRGGBB.
	#     Examples: "#F4C", "0xFEE0", "#40FF2E", "#CC00E2EE"
	#
	#   Decimal color code - A decimal color code, which is just a hex color code converted to decimal.  May or may not be quoted.
	#     Examples: 15614720, "4278251143"
	#
	#   Minecraft color name - One of the standard 16 Minecraft color names.  Must be quoted.
	#     Examples: "red", "dark_purple", "gold"
	#
	#   Web color name - One of the standard 140 web/HTML color names or "transparent".  Must be quoted.
	#     Examples: "chartreuse", "darkorange", "deeppink", "deepskyblue"
	#
	#   Modifiers - Colors specified in any of the above formats can be modified by using modifiers.
	#         Modifiers are specified after any color in the format "<+, -, or =><h, s, v, r, g, b, or a><amount>".
	#         The letters represent h - hue, s - saturation, v - value, r - red, g - green, b - blue, a - alpha.
	#         Valid amounts are 0 to 255 for all types except hue, which accepts 0 to 359.
	#     Examples: "red+h15", "#saddlebrown-v20+s5", "10_aqua_aqua+v15-h5", "#F4C-r15-v10=a40"
	#
	#   Animated color - An animated color that fades from one to another in sequence.
	#         A string in the format "<duration in seconds>_<list of color definitions separated by underscores>".  Must be quoted.
	#     Examples: "10_black_#7FFF00", "5.5_gold_orange_orangered", "20_red_orange_yellow_green_blue_purple"
	[client.colors]
		level0_colors = ["20_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922+v64-s32_#FF996922", "20_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF996922+v64-s32", "#D0996922-v155", "#F45A3A1D-v55"]
		level1_colors = ["20_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C+v48-s16_#FF697C8C", "20_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61+v48-s16", "#D0697C8C-v155", "#F43A4C61-v65"]
		level2_colors = ["20_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D+v64-s32_#FF70453D", "20_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323+v64-s32", "#D070453D-v155", "#F4542323-v60"]
		level3_colors = ["30_#FF912307_orangered-s45-v25_#FF912307+v50_#FF912307+r25+s50-v55", "30_#FF818385-v15_#FF818385+r5+g5+v45_#FF818385-v45_#FF818385+r25+g25", "30_#FF912307-v105-a36_#F0120A00", "#F8818385-v100"]
		level4_colors = ["24_#FF008FCC-v25_#FF008FCC+s25+v85", "24_#FF044B8A-v30_#FF044B8A+s25+v55", "#D0008FCC-v160", "#F8044B8A-v75"]
		level5_colors = ["#FF5C4C2D", "#FF5C4C2D", "#F0160A00", "#F0160A00"]
		level6_colors = ["#FF705A87", "#FF705A87-v70+s15", "#E8705A87-v85+s15", "#F4705A87-v120+s35"]
		level7_colors = ["#FF7D8A91", "#FF7D8A91", "#F07D8A91-v125+s35", "#F47D8A91-v100+s55"]
		level8_colors = ["#FFA591B6", "#FFA591B6", "#E4A591B6-v155+s35", "#F4A591B6-v145+s35"]
		level9_colors = ["15_#FFFFFADB-v20+s35_#FFFFFADB+v30-s20", "15_#FFFFDFAD-v20+s35_#FFFFDFAD+v30-s20", "#D8FFFADB-v245", "#F4FFDFAD-v210+s90"]
		level10_colors = ["auto", "auto", "auto", "auto"]
		level11_colors = ["auto", "auto", "auto", "auto"]
		level12_colors = ["auto", "auto", "auto", "auto"]
		level13_colors = ["auto", "auto", "auto", "auto"]
		level14_colors = ["auto", "auto", "auto", "auto"]
		level15_colors = ["auto", "auto", "auto", "auto"]

#{
#	"definitions": [
#		// 3.  Smoke and flames
#		{
#			"index": 3,
#			"startColor": "30_#FF912307_orangered-s45-v25_#FF912307+v50_#FF912307+r25+s50-v55",
#			"endColor": "30_#FF818385-v15_#FF818385+r5+g5+v45_#FF818385-v45_#FF818385+r25+g25",
#			"bgStartColor": "30_#FF912307-v105-a36_#F0120A00",
#			"bgEndColor": "#F8818385-v100",
#			"selectors": ["%Nether B", "%Nether Q", "%Nether G", "netherrack", "%Nylium", "crimson_fungus", "warped_fungus", "campfire", "fire_charge", "%Firework", "%Lava"]
#		},
#		// 4.  Water / Ice
#		{
#			"index": 4,
#			"startColor": "24_#FF008FCC-v25_#FF008FCC+s25+v85",
#			"endColor": "24_#FF044B8A-v30_#FF044B8A+s25+v55",
#			"bgStartColor": "#D0008FCC-v160",
#			"bgEndColor": "#F8044B8A-v75",
#			"selectors": ["sea_lantern", "heart_of_the_sea", "%Prismarine", "conduit", "nautilus_shell"]
#		},
#		// 5.  Rose and vines
#		{
#			"index": 5,
#			"startColor": "#FF5C4C2D",
#			"endColor": "#FF5C4C2D",
#			"bgStartColor": "#F0160A00",
#			"bgEndColor": "#F0160A00",
#			"selectors": ["$minecraft:small_flowers", "$minecraft:flowers", "$minecraft:leaves", "$minecraft:saplings", "$minecraft:tall_flowers", "%Azalea", "%Dripleaf", "%Vines", "bamboo"]
#		},
#		// 6.  Bones / death
#		{
#			"index": 6,
#			"startColor": "#FF705A87",
#			"endColor": "#FF705A87-v70+s15",
#			"bgStartColor": "#E8705A87-v85+s15",
#			"bgEndColor": "#F4705A87-v120+s35",
#			"selectors": ["%Skull", "wither_rose", "%Obsidian", "respawn_anchor", "%Soul"]
#		},
#		// 7.  Iron plating / machinery
#		{
#			"index": 7,
#			"startColor": "#FF7D8A91",
#			"endColor": "#FF7D8A91",
#			"bgStartColor": "#F07D8A91-v125+s35",
#			"bgEndColor": "#F47D8A91-v100+s55",
#			"selectors": ["iron_door", "iron_trapdoor", "iron_block", "%Anvil", "%Minecart", "%Rail", "hopper", "observer", "dispenser", "dropper", "%Piston"]
#		},
#		// 8.  Purple geometric motif
#		{
#			"index": 8,
#			"startColor": "#FFA591B6",
#			"endColor": "#FFA591B6",
#			"bgStartColor": "#E4A591B6-v155+s35",
#			"bgEndColor": "#F4A591B6-v145+s35",
#			"selectors": ["%End", "%Purpur", "%Chorus", "%Shulker"]
#		},
#		// 9.  Holy (halo / wings)
#		{
#			"index": 9,
#			"startColor": "15_#FFFFFADB-v20+s35_#FFFFFADB+v30-s20",
#			"endColor": "15_#FFFFDFAD-v20+s35_#FFFFDFAD+v30-s20",
#			"bgStartColor": "#D8FFFADB-v245",
#			"bgEndColor": "#F4FFDFAD-v210+s90",
#			"selectors": ["elytra", "%Glow", "totem_of_undying", "experience_bottle", "golden_carrot", "golden_apple", "enchanted_golden_apple"]
#		},
#		// 0.  Gold frame
#		{
#			"index": 0,
#			"startColor": "20_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922_#FF996922+v64-s32_#FF996922",
#			"endColor": "20_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF5A3A1D_#FF996922+v64-s32",
#			"bgStartColor": "#D0996922-v155",
#			"bgEndColor": "#F45A3A1D-v55",
#			"selectors": ["netherite_sword", "netherite_shovel", "netherite_pickaxe", "netherite_axe", "netherite_hoe", "netherite_helmet", "netherite_chestplate", "netherite_leggings", "netherite_boots",
#						  "!epic"]
#		},
#		// 1.  Silver frame
#		{
#			"index": 1,
#			"startColor": "20_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C_#FF697C8C+v48-s16_#FF697C8C",
#			"endColor": "20_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61_#FF3A4C61+v48-s16",
#			"bgStartColor": "#D0697C8C-v155",
#			"bgEndColor": "#F43A4C61-v65",
#			"selectors": ["diamond_sword", "diamond_shovel", "diamond_pickaxe", "diamond_axe", "diamond_hoe", "diamond_helmet", "diamond_chestplate", "diamond_leggings", "diamond_boots",
#						  "enchanted_book", "turtle_helmet", "tipped_arrow", "spectral_arrow", "!rare"]
#		},
#		// 2.  Copper frame
#		{
#			"index": 2,
#			"startColor": "20_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D_#FF70453D+v64-s32_#FF70453D",
#			"endColor": "20_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323_#FF542323+v64-s32",
#			"bgStartColor": "#D070453D-v155",
#			"bgEndColor": "#F4542323-v60",
#			"selectors": ["iron_sword", "iron_shovel", "iron_pickaxe", "iron_axe", "iron_hoe", "iron_helmet", "iron_chestplate", "iron_leggings", "iron_boots",
#						  "golden_sword", "golden_shovel", "golden_pickaxe", "golden_axe", "golden_hoe", "golden_helmet", "golden_chestplate", "golden_leggings", "golden_boots",
#						  "%Chainmail", "compass", "clock", "spyglass", "shears", "%Bucket", "lead", "name_tag", "flint_and_steel", "bow", "crossbow", "trident", "shield"]
#		}
#	]
#}